apiVersion: apps/v1
kind: Deployment
metadata:
  name: "go-api"
  namespace: application
  labels:
    app: "go"
spec:
  replicas: 5
  selector:
    matchLabels:
      app: "go"
  template:
    metadata:
      labels:
        app: "go"
    spec:
      containers:
        - name: "go-api"
          image: "rafael556/go-api:v5"
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
