apiVersion: v1
kind: Service
metadata:
  name: "{{ .Release.Name }}-go-api-service"
  namespace: "{{ .Values.namespace }}"
  labels:
    app: "{{ .Values.appName }}"
spec:
  type: NodePort
  ports:
    - port: {{ .Values.servicePort }}
      targetPort: {{ .Values.targetPort }}
      protocol: TCP
      name: http
  selector:
    app: "{{ .Values.appName }}"
