apiVersion: v1
kind: Service
metadata:
  name: "go-api"
  namespace: application
  labels:
    app: "go"
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: "go"
