---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "go-api"
spec:
  project: devops
  source:
    repoURL: https://github.com/rafacostatmaior/argo-go-test
    targetRevision: HEAD
    chart: go-api
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - Validate=true
      - CreateNamespace=true
      - PrunePropagationPolicy-foreground
      - PruneLast=true