---
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: "go-api"
spec:
  project: default
  source:
    repoURL: https://github.com/rafacostatmaior/argo-go-test
    targetRevision: HEAD
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: application
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=false